[[redirects]]
  from = "/api/*"
  to = "http://ec2-13-209-224-77.ap-northeast-2.compute.amazonaws.com:8080/:splat"
  status = 200
  force = true

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
